### ISSUE TITLE
Question: What do I need the 'get' topic for?

### ISSUE THREAD

**Issue by robrec** [mhawkshaw/homebridge-mqttsmokesensor#1]
Hi,

thanks for your work.

I wonder what the 'get' topics are for, as the functions work even without them. Unfortunately, I can't find this information in the description.

Thank you

**Comment by mhawkshaw** [comment]
Hi,

It's not strictly necessary. It should be that your smoke sensor is sending the changes directly over MQTT which is then picked up by this plug-in, which then updates the accessory information. Obviously is smoke is detected, you want to pass the information on straight away!

When you query the smoke alarm in the Home App, it fetches the latest information from the plug-in, which then triggers these "get" topics to ensure the information is up-to-date. However, the status is cached anyway so if these topics go unanswered it won't affect showing the information in the Home App.

Hope this helps.
